apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: k8s-config
spec:
  selector:
    matchLabels:
      app: k8s-config
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: k8s-config
    spec:
      containers:
        - name: k8s-config
          image: k8s-config:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running in the cluster